on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Setup Docker (for MacOS)
      uses: docker-practice/actions-setup-docker@master
      if: runner.os == 'macOS'

    - name: Switch Windows Docker Daemon to Linux Images
    - run: |
        "%programfiles%\docker\docker\dockercli.exe" -SwitchDaemon
      if: runner.os == 'Windows'

    - run: npm install

    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'

    - run: npm test
      if: runner.os != 'Linux'